name: SimpleQuests
version: '${version}'
main: dev.jsinco.simplequests.SimpleQuests
api-version: '1.20'
author: Jsinco
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:2.0.21'
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
commands:
  simplequests:
    description: Main command for SimpleQuests
    permission: simplequests.command
    aliases:
      - quests
      - sq
permissions:
  simplequests.command:
    description: Command permission for SimpleQuests
    default: op
  simplequests.maxquests.<category>.<amount>:
    description: Maximum quests permission for SimpleQuests
    default: false
  simplequests.quest.all.amount:
    description: Amount of all quests permission for SimpleQuests
    default: false